-- V1__init.sql
-- Inicialización del esquema + datos de ejemplo del enunciado

CREATE TABLE prices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  brand_id   BIGINT    NOT NULL,
  start_date TIMESTAMP NOT NULL,
  end_date   TIMESTAMP NOT NULL,

  price_list INT       NOT NULL,
  product_id BIGINT    NOT NULL,
  priority   INT       NOT NULL,

  price DECIMAL(10,2)  NOT NULL,
  curr  VARCHAR(3)     NOT NULL
);

-- Índices orientados al caso de uso: buscar por brand+product y filtrar por rango de fechas
CREATE INDEX idx_prices_brand_product_dates
  ON prices (brand_id, product_id, start_date, end_date);

-- Índice para ayudar a ordenar/seleccionar por prioridad en la misma combinación brand+product
CREATE INDEX idx_prices_brand_product_priority
  ON prices (brand_id, product_id, priority);

-- Datos del enunciado
INSERT INTO prices (brand_id, start_date, end_date, price_list, product_id, priority, price, curr)
VALUES
  (1, TIMESTAMP '2020-06-14 00:00:00', TIMESTAMP '2020-12-31 23:59:59', 1, 35455, 0, 35.50, 'EUR'),
  (1, TIMESTAMP '2020-06-14 15:00:00', TIMESTAMP '2020-06-14 18:30:00', 2, 35455, 1, 25.45, 'EUR'),
  (1, TIMESTAMP '2020-06-15 00:00:00', TIMESTAMP '2020-06-15 11:00:00', 3, 35455, 1, 30.50, 'EUR'),
  (1, TIMESTAMP '2020-06-15 16:00:00', TIMESTAMP '2020-12-31 23:59:59', 4, 35455, 1, 38.95, 'EUR');
